<div class="footer_contacts">
    <div class="footer-title-border"></div>
    <div class="links">
        <p class="mlp_title"> MLP BARREIRO LDA </p>
        <p>Rua Rei da Memória nº14</p>
        <p>2475-149 Benedita</p>
        <a class="mlp_contact_link" href="tel:262921512" target="_blank"><p>262921512</p></a>
        <a class="mlp_contact_link" href="mailto:mlpbarreiro@gmail.com"><p>mlpbarreiro@gmail.com</p></a>
        <a class="mlp_contact_link" href="https://goo.gl/maps/ikXnSMHdfHbWA1K1A" target="_blank"><p>Veja no mapa</p></a>
    <div>
</div>