<div class="footer_contacts">
    
        <p class="mlp_title"> MLP BARREIRO LDA </p>
        <p><a class="mlp_contact_link" href="tel:262921512" target="_blank"><i class="fas fa-phone"></i> 262921512</a></p>
        <p><a class="mlp_contact_link" href="mailto:mlpbarreiro@gmail.com"><i class="fa fa-envelope" aria-hidden="true"></i> mlpbarreiro@gmail.com</a></p>
        <p><a class="mlp_contact_link" href="https://goo.gl/maps/ikXnSMHdfHbWA1K1A" target="_blank"><i class="fas fa-map-marker-alt"></i> Veja no mapa</a></p>
        <p><a href="https://api.whatsapp.com/send?phone=351917064925"><i class="fab fa-whatsapp"></i> Whatsapp</a></p>
        <p><a href="m.me/mlpbarreiro"><i class="fab fa-facebook-messenger"></i> Messenger</a></p>
</div>